MobileStore_CodeFirst/MobileStore_CodeFirst/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileStore_CodeFirst.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MobileStore_CodeFirst/MobileStore_CodeFirst/Controllers/MobileModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MobileStore_CodeFirst.Models;
using MobileStore_CodeFirst.Models.MobileEDM;

namespace MobileStore_CodeFirst.Controllers
{
    public class MobileModelsController : Controller
    {
        private MobileContext db = new MobileContext();

        // GET: MobileModels
        public ActionResult Index()
        {
            var models = db.Models.Include(m => m.Brand).Include(m => m.OPSystem);
            return View(models.ToList());
        }

        // GET: MobileModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MobileModel mobileModel = db.Models.Find(id);
            if (mobileModel == null)
            {
                return HttpNotFound();
            }
            return View(mobileModel);
        }

        // GET: MobileModels/Create
        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName");
            ViewBag.OPSystemId = new SelectList(db.OperatingSystems, "OPSystemId", "OpSystemName");
            return View();
        }

        // POST: MobileModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MobileModelId,ModelName,BrandId,Price,RAM,StorageCapacity,OPSystemId")] MobileModel mobileModel)
        {
            if (ModelState.IsValid)
            {
                if (CanAddModel(mobileModel.ModelName))
                {
                    db.Models.Add(mobileModel);
                    db.SaveChanges();
                    TempData["ModelStatusMessage"] = "Model has been added successfully!";
                    return RedirectToAction("Index");
                }
                DisplayModelExistsMessage(mobileModel);
            }

            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName", mobileModel.BrandId);
            ViewBag.OPSystemId = new SelectList(db.OperatingSystems, "OPSystemId", "OpSystemName", mobileModel.OPSystemId);
            return View(mobileModel);
        }

        // GET: MobileModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MobileModel mobileModel = db.Models.Find(id);
            if (mobileModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName", mobileModel.BrandId);
            ViewBag.OPSystemId = new SelectList(db.OperatingSystems, "OPSystemId", "OpSystemName", mobileModel.OPSystemId);
            return View(mobileModel);
        }

        // POST: MobileModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MobileModelId,ModelName,BrandId,Price,RAM,StorageCapacity,OPSystemId")] MobileModel mobileModel)
        {
            if (ModelState.IsValid)
            {
                if (CanUpdateModel(mobileModel))
                {
                    db.Entry(mobileModel).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["ModelStatusMessage"] = "Model has been updated successfully!";
                    return RedirectToAction("Index");
                }
                DisplayModelExistsMessage(mobileModel);
            }
            ViewBag.BrandId = new SelectList(db.Brands, "BrandId", "BrandName", mobileModel.BrandId);
            ViewBag.OPSystemId = new SelectList(db.OperatingSystems, "OPSystemId", "OpSystemName", mobileModel.OPSystemId);
            return View(mobileModel);
        }

        // GET: MobileModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MobileModel mobileModel = db.Models.Find(id);
            if (mobileModel == null)
            {
                return HttpNotFound();
            }
            return View(mobileModel);
        }

        // POST: MobileModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MobileModel mobileModel = db.Models.Find(id);
            db.Models.Remove(mobileModel);
            TempData["ModelStatusMessage"] = "Model has been deleted successfully!";
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool CanAddModel(string modelName)
        {
            var query = db.Models.Any(m => m.ModelName == modelName);
            return !query;
        }

        private bool CanUpdateModel(MobileModel mbM)
        {
            var query = db.Models.Where(m => m.MobileModelId != mbM.MobileModelId).Any(m => m.ModelName == mbM.ModelName);
            return !query;
        }
        private void DisplayModelExistsMessage(MobileModel m)
        {
            ModelState.AddModelError("ModelName", $"Model {m.ModelName} already exists please choose another name.");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MobileStore_CodeFirst/MobileStore_CodeFirst/Controllers/OPSystemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MobileStore_CodeFirst.Models;
using MobileStore_CodeFirst.Models.MobileEDM;

namespace MobileStore_CodeFirst.Controllers
{
    public class OPSystemsController : Controller
    {
        private MobileContext db = new MobileContext();

        // GET: OPSystems
        public ActionResult Index()
        {
            return View(db.OperatingSystems.ToList());
        }

        // GET: OPSystems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPSystem oPSystem = db.OperatingSystems.Find(id);
            if (oPSystem == null)
            {
                return HttpNotFound();
            }
            return View(oPSystem);
        }

        // GET: OPSystems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OPSystems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OPSystemId,OpSystemName,Description")] OPSystem oPSystem)
        {
            if (ModelState.IsValid)
            {
                if (CanAddOPSystem(oPSystem.OpSystemName))
                {
                    db.OperatingSystems.Add(oPSystem);
                    db.SaveChanges();
                    TempData["OPSystemStatusMessage"] = "Operating system has been added successfully!";
                    return RedirectToAction("Index");
                }
                DisplayOPSystemExistsMessage(oPSystem);
            }

            return View(oPSystem);
        }

        // GET: OPSystems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPSystem oPSystem = db.OperatingSystems.Find(id);
            if (oPSystem == null)
            {
                return HttpNotFound();
            }
            return View(oPSystem);
        }

        // POST: OPSystems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OPSystemId,OpSystemName,Description")] OPSystem oPSystem)
        {
            if (ModelState.IsValid)
            {
                if (CanUpdateOPSystem(oPSystem))
                {
                    db.Entry(oPSystem).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["OPSystemStatusMessage"] = "Operating system has been updated successfully!";
                    return RedirectToAction("Index");
                }
                DisplayOPSystemExistsMessage(oPSystem);
            }
            return View(oPSystem);
        }

        // GET: OPSystems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPSystem oPSystem = db.OperatingSystems.Find(id);
            if (oPSystem == null)
            {
                return HttpNotFound();
            }
            return View(oPSystem);
        }

        // POST: OPSystems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SetForeignKeysToNull(id);
            OPSystem oPSystem = db.OperatingSystems.Find(id);
            db.OperatingSystems.Remove(oPSystem);
            db.SaveChanges();
            TempData["OPSystemStatusMessage"] = "Operating system has been deleted successfully!";
            return RedirectToAction("Index");
        }

        private bool CanAddOPSystem(string opsName)
        {
            var query = db.OperatingSystems.Any(o => o.OpSystemName == opsName);
            return !query;
        }
        private bool CanUpdateOPSystem(OPSystem opS)
        {
            var query = db.OperatingSystems.Where(o => o.OPSystemId != opS.OPSystemId).Any(o => o.OpSystemName == opS.OpSystemName);
            return !query;
        }
        private void DisplayOPSystemExistsMessage(OPSystem o)
        {
            ModelState.AddModelError("OpSystemName", $"Model {o.OpSystemName} already exists please choose another name.");
        }

        private void SetForeignKeysToNull(int id)
        {
            var opSys = db.OperatingSystems.Find(id);

            var query = from m in opSys.Models
                        where m.OPSystemId == opSys.OPSystemId
                        select new { m };

            query.ToList().ForEach(x => x.m.OPSystemId = null);

            db.Entry(opSys).State = EntityState.Modified;
            db.SaveChanges();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MobileStore_CodeFirst/MobileStore_CodeFirst/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MobileStore_CodeFirst/MobileStore_CodeFirst/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MobileStore_CodeFirst/MobileStore_CodeFirst/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div id="home">
</div>

<div class="p-5">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <img src="~/Content/img/Mobile_app.svg" />
            </div>
            <div class="col-sm-6 text-center align-self-center">
                <h2 class="pb-2">Let's Find a Mobile For You!</h2>
                <p class="lead">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Id laboriosam magnam error expedita fugit. Repellendus magni, accusamus aspernatur fugit esse sequi corporis? Ad, enim est?
                </p>
                <p class="lead">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos deserunt quisquam dolores sunt, fugit molestias suscipit accusantium sed, sequi architecto enim dignissimos voluptatum tenetur aperiam.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="p-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor vitae itaque rerum eligendi, deleniti quas error, mollitia aliquam quisquam facilis hic officiis eum voluptatum reprehenderit, autem praesentium nemo necessitatibus dolore magnam voluptates quibusdam rem. Autem placeat optio quo aliquam.
                </p>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 d-flex justify-content-center align-content-center">
                <img src="~/Content/img/apple-brands.svg" class="img-fluid w-50"/>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-12">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor vitae itaque rerum eligendi, deleniti quas error, mollitia aliquam quisquam facilis hic officiis eum voluptatum reprehenderit, autem praesentium nemo necessitatibus dolore magnam voluptates quibusdam rem. Autem placeat optio quo aliquam.
                </p>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 d-flex justify-content-center align-content-center">
                <img src="~/Content/img/samsung.svg" class="img-fluid" />
            </div>
        </div>
    </div>
</div>

<div id="mobile-background">
</div>

<div class="p-5">
    <div class="container">
        <div class="row d-flex justify-content-between">
            <div class="col-sm-3 border border-dark rounded p-0 m-2 text-center">
                <img src="~/Content/img/brands.jpg" class="img-fluid rounded img-links"/>
                <h3>@Html.ActionLink("Brands", "Index", "Brands", null, new { @class = "text-decoration-none" })</h3>
                <p class="p-1">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies fringilla lacus nec sollicitudin. Pellentesque ullamcorper aliquam libero ac vehicula. Cras tempus aliquam tincidunt. Nam orci lorem, cursus eget laoreet.
                </p>
            </div>
            <div class="col-sm-3 border border-dark rounded p-0 m-2 text-center">
                <img src="~/Content/img/models.jpg" class="img-fluid rounded img-links" />
                <h3>@Html.ActionLink("Models", "Index", "MobileModels", null, new { @class = "text-decoration-none" })</h3>
                <p class="p-1">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies fringilla lacus nec sollicitudin. Pellentesque ullamcorper aliquam libero ac vehicula. Cras tempus aliquam tincidunt. Nam orci lorem, cursus eget laoreet.
                </p>
            </div>
            <div class="col-sm-3 border border-dark rounded p-0 m-2 text-center">
                <img src="~/Content/img/opsystems.jpg" class="img-fluid rounded img-links" />
                <h3>@Html.ActionLink("Operating Systems", "Index", "OPSystems", null, new { @class = "text-decoration-none" })</h3>
                <p class="p-1">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies fringilla lacus nec sollicitudin. Pellentesque ullamcorper aliquam libero ac vehicula. Cras tempus aliquam tincidunt. Nam orci lorem, cursus eget laoreet.
                </p>
            </div>
        </div>
    </div>
</div>
@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@